### ISSUE TITLE
Link tag

### ISSUE THREAD

**Issue by Olanrewaju-dev** [mishael-codes/navbar-package#1]
Hello Mishael. 

I love your Open Source navbar projects. The animation is smooth on mobile as well. 

I wanted to contribute by fixing the link tag to ensure it resolves to the right styling and script files. Right now, it doesn't. Must be an ommission.

**Comment by mishael-codes** [comment]
Hello Olanrewaju,

Thank you for your kind words about my open-source navbar projects. However, it seems you raised the issue in the wrong project. Please create it in the appropriate repository for the navbar you are referring to. We appreciate your contribution.
